base_url = "https://isunjn.me"
title = "isunjn"
description = "Personal website of @isunjn"
default_language = "zh-CN"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Jianan Sun"
id = "isunjn"
bio = "programmer, he/him, we are young and life is fun"
avatar = "img/avatar.webp"

display_id = true
display_bio = true
display_avatar = false

recent = false
recent_max = 5
recent_more_text = "more »"

sections = [
  { name = "posts", path = "/posts", is_external = false },
  { name = "projects", path = "/projects", is_external = false },
  { name = "favs", path = "/favs", is_external = false },
]
blog_section_path = "/posts"

links = [
  { name = "GitHub", icon = "github", url = "https://github.com/isunjn" },
  { name = "Email", icon = "email", url = "mailto:isunjn@gmail.com" },
  { name = "GPG", icon = "fingerprint", url = "https://github.com/isunjn.gpg" },
]

force_theme = false
blog_categorized = false
blur_effect = false
toc = false
copy = true
back_to_top = true
comment = false

reaction = true
reaction_align = "right"
reaction_endpoint = "https://reaction.isunjn.workers.dev"

outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "本文最后更新于 "
outdate_alert_text_after = " 天前，部分内容可能已失去时效性"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

footer_copyright = "© 2024 isunjn"
footer_credits = true

not_found_title = "404"
not_found_error_text = "not found"
not_found_recover_text = "« back to home »"
