base_url = "https://isunjn.me"
title = "isunjn::self"
description = "Personal website of @isunjn"
default_language = "zh-CN"
theme = "serene"
output_dir = "docs"
compile_sass = true
minify_html = false
build_search_index = false
generate_feed = false
feed_filename = "feed.xml"
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Jianan Sun"
id = "isunjn"
bio = "In programming we trust"
avatar = "img/avatar.webp"
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/isunjn" },
    { name = "Twitter", icon = "twitter", url = "https://twitter.com/isunjn" },
    { name = "GPG", icon = "fingerprint", url = "https://github.com/isunjn.gpg" },
]

nav_separator = "::"

display_id = true
projects_page = true
blog_categorized = false
blur_effect = true

toc = true
comment = true

outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "本文最后更新于 "
outdate_alert_text_after = " 天前，部分内容可能已失去时效性，请谨慎参考"

footer_copyright = "© 2023 isunjn"
footer_credits = true
